config/routes.rb
York::Application.routes.draw do
  

  

 	scope '(:locale)' do
		mount RailsAdmin::Engine => '/members', :as => 'rails_admin'
		devise_for :admins
		devise_for :users
		delete 'likes/:resource_name/:resource_id' => "likes#destroy", as: 'like'
		post 'likes/:resource_name/:resource_id' => "likes#create", as: 'like'
		mount Ckeditor::Engine => '/ckeditor'
		resources :abouts
    resources :servers
		resources :topics
		match '/contact' => 'topics#contact'
		resource :cart
		resources :line_items
		resources :products
		resources :product_users
		resources :orders
		resources :customers
		resources :categories
		resources :directories
		match '/tags' => 'categories#tags'
		match 'visit' => 'product_users#visit'
		match '/like' => 'products#like'
		match '/liked' => 'products#liked'
		match '/search' => 'products#search'
		root to: 'home#index'
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
			if params[:set_locale]
			redirect_to root_path(locale: params[:set_locale])
		else
			@products = Product.all
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_image.html.erb
<script>
		// 需要你写的数据
		var data = [
		<% Product.all.each do |product| %>
			{title:"<%= product.title %>",desc:'立刻加入我们',src:"<%= product.photos.first.image_url%>"},
	<% end %>
		];
		$(document).ready(function(){
			$('#pic').d_imagechange({
				data:data,
				width:785,
				height:297,
				animateStyle:'o',
				animateTime:1000,
			});
		});
	</script>

app/views/home/_index_products.html.erb
<% Category.all.each do |cate| %>
	<div class="show-product">
		<div id="tabbox">
			<ul class="tabs" id="tabs">
				<ol><%= link_to cate.name, cate %></ol>
				<% cate.tags.each do |tag| %>
					<li><%= link_to tag.name, "#" %></li>
				<% end %>
			</ul>
			<ul class="tab_conbox" id="tab_conbox">
				<% cate.tags.each do |tag| %>
					<li class="tab_con">
					<div class="row-fluid">
						<ul class="thumbnails">
							<% tag.lists.limit(1).each do |list| %>
								<div id="media"><%= link_to "查看更多", tags_path(t:tag) %></div>
								<% list.products.each do |product| %>
									<ol>
										<div class="thumbnail">
											<%= link_to image_tag(product.photos.first.image_url), product_path(product) %>
											<div class="caption">
												<h5><%= product.title %></h5>
												<small><%= product.number %></small>
												<small><%= product.use %></small>
												<p><%= raw truncate(product.content, length: 34) %></p>
											</div>
										</div>
									</ol>
								<% end %>
							<% end %>
						</ul>
					</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>
<script type="text/javascript">
	$(document).ready(function() {
			jQuery.jqtab = function(tabtit,tab_conbox,shijian) {
			$(tab_conbox).find("li").hide();
			$(tabtit).find("li:first").addClass("thistab").show(); 
			$(tab_conbox).find("li:first").show();
			$(tabtit).find("li").bind(shijian,function(){
				$(this).addClass("thistab").siblings("li").removeClass("thistab"); 
				var activeindex = $(tabtit).find("li").index(this);
				$(tab_conbox).children().eq(activeindex).show().siblings().hide();
				return false;
				});
			};
			$.jqtab(".tabs",".tab_conbox","click");
	});
</script>

app/views/home/_like_view.html.erb
<div class="show-product">
	<ul class="like_view">
		<ol><span>关注最多</span></ol>
	</ul>
	<div class="row-fluid">
		<ul class="thumbnails">
			<% Product.order("liked_count desc").limit(4).each do |product| %>
		<%= render partial: 'products/like_view', locals: {product: product} %>
	<% end %>
</div>
</ul>
</div>
<div class="show-product">
	<ul class="like_view">
		<ol><span>访问最多</span></ol>
	</ul>
	<div class="row-fluid">
		<ul class="thumbnails">
			<% Product.order("view_count desc").limit(4).each do |product| %>

				<%= render partial: 'products/like_view', locals: {product: product} %>
			<% end %>
		</ul>
	</div>
</div>

app/views/home/index.html.erb
<!-- 调试 -->
<%= render partial: "products/nav_list" %>
<div class="index-img">
	<%= render 'image' %>
		<div id="pic" style="width:745px;height:297px;margin:auto">	
	</div>
</div>
<%= render 'like_view' %>
<%= render 'index_products' %>
<div class="footer-nav">
	<div class="about-us">
	<ul>
		<li><%= link_to "关于我们", "#" %></li>
	</ul>
	<img src="/assets/1.jpg" />
	<div class="span-font">
	<span>
		ROBT在工业设备扩
		展的谈说道路上走出了
		一条技术领先的道路,
		ROBT在工业设备扩
		展的谈说道路上走出
		了一条技术领先的道
	</span>
</div>
</div>
<div class="new-robt">
	<ul>
		<li><%= link_to "新闻中心","#" %></li>
	</ul>
	<table class="table">
		<tbody>
			<tr><td>关于某些网站盗用公司图片，资料严正声明.</td></tr>
			<tr><td>热烈庆祝罗倍拓国内销售额翻番</td></tr>
			<tr><td>物料搬运设备市场，ROBT持续稳重求进</td></tr>
		</tbody>
	</table>
</div>
<div class="mulu">
	<ul>
		<li><%= link_to "免费索取工业设备目录", new_directory_path %></li>
	</ul>
	<img src="/assets/2.jpg" />
</div>
</div>


<!--正文-->
<div id="myCarousel" class="carousel slide">
<ol class="carousel-indicators">
	<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	<li data-target="#myCarousel" data-slide-to="1"></li>
	<li data-target="#myCarousel" data-slide-to="2"></li>
</ol>
<!-- Carousel items -->
<div class="carousel-inner">
	<div class="active item"><img src="/assets/1.jpg"></div>
	<div class="item"><img src="/assets/2.jpg"></div>
	<div class="item"><img src="/assets/6.jpg"></div>
</div>
<!-- Carousel nav -->
<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<script>
	$('.carousel').carousel({
		  interval: 5000
		})
</script>
<div class="well">
	<h5 style="text-align: center">关注最多</h2>
</div>
<div class="row-fluid">
	<ul class="thumbnails">
		<% Product.order("liked_count desc").limit(4).each do |product| %>
			<li>
			<div class="thumbnail">
				<%= link_to image_tag(product.photos.first.image_url),product%>
				<h5>	<%= product.title %></h5>
				<small><%= product.number %></small>
				<small><%= product.use %></small>
				<p><%= truncate(product.content, length: 24) %></p>
			</div>
			</li>
		<% end %>
	</ul>
</div>
<div class="well">
	<h5 style="text-align: center">访问最多</h2>
</div>
<%= render partial: 'product_users/visit_list', locals: {products: @products} %>

app/views/home/index2.html.erb
<script type="text/javascript">
	$(document).ready(function() {
			jQuery.jqtab = function(tabtit,tab_conbox,shijian) {
			$(tab_conbox).find("li").hide();
			$(tabtit).find("li:first").addClass("thistab").show(); 
			$(tab_conbox).find("li:first").show();
			$(tabtit).find("li").bind(shijian,function(){
				$(this).addClass("thistab").siblings("li").removeClass("thistab"); 
				var activeindex = $(tabtit).find("li").index(this);
				$(tab_conbox).children().eq(activeindex).show().siblings().hide();
				return false;
				});
			};
			$.jqtab("#tabs","#tab_conbox","click");
			$.jqtab("#tabs2","#tab_conbox2","click");
	});
</script>
<!-- 调试 -->
<div class="index-top">
	<ul>
		<li>登录 |</li>
		<li>注册</li>
		<li>English</li>
	</ul>
</div>
<div class="index-logo">
	<div class="ps-index">
	<img src="/assets/rails.png" />
	<div class="logo-font">
	<span>工业仓储设备专家</span>
	<br />
	<small>便捷订购</small>
	<small>一站式服务</small>
	<small>致力与服务企业客户</small>
</div>
</div>
<div class="ps-index">
<img src="/assets/rails.png">
<div class="logo-font">
	<span>400 8826 918</span>
	<br />
	<small>产品咨询时间：周一～周六 8:30--17:30</small>
</div>
</div>
</div>
<div class="index-nav">
	<ul>
		<li>			首页	 </li>
		<li>	 产品中心	 </li>
		<li>	 关于我们	 </li>
		<li>	 服务中心	 </li>
		<li>			新闻	 </li>
		<li>	 联系我们  </li>
		<li><input type="text" name="q" placeholder="请输入产品名称或货号">
		<button type="submit">搜索</button>
		</li>
		<li>
		<span class="badge badge-important">
			0
		</span>
		<i class="icon-shopping-cart"></i>
			</li>
	</ul>
</div>
<div class="search-font">
	<small>热门搜索：高空作业车 电动堆高车  电动搬运车 小推车</small>
</div>
<div class="nav-list">
	<h3>产品目录</h3>
	<ul>
		<li>高空作业平台</li>
		<li>堆高设备</li>
		<li>搬运设备</li>
		<li>升降平台</li>
		<li>起重吊运</li>
		<li>仓储设备</li>
		<li>工位装备</li>
	</ul>
</div>
<div class="index-img">
	<%= render 'image' %>
		<div id="pic" style="width:745px;height:297px;margin:auto">	
	</div>
</div>

		
	<div class="show-product">
	<div id="tabbox">
	<ul class="tabs" id="tabs">
		<ol>高空作业</ol>	
		<li><a href="#">桅柱式高空作业平台</li>
		<li><a href="#">剪叉式高空作业平台</a></li>
		<li><a href="#">直臂式高空作业平台</a></li>
		<li><a href="#">曲臂式高空作业平台</a></li>
		<li><a href="#">高位取货车</a></li>
		<li><a href="#">工业用梯</a></li>
		</ul>
		<ul class="tab_conbox" id="tab_conbox">
			<li class="tab_con">
			<img src="assets/6.jpg" />
			<img src="assets/6.jpg" />
			<img src="assets/6.jpg" />
			<img src="assets/6.jpg" />
			</li>
			<li class="tab_con">
			<img src="assets/6.jpg"/>
			</li>
<li class="tab_con">
			<img src="assets/2.jpg"/>
<img src="assets/2.jpg"/>
<img src="assets/2.jpg"/>
			</li>
		</ul>
	</div>
</div>
<div class="show-product">
	<div id="tabbox">
	<ul class="tabs" id="tabs2">
		<li>高空作业</li>	
		<li><a href="#">桅柱式高空作业平台</li>
		<li><a href="#">剪叉式高空作业平台</a></li>
		<li><a href="#">直臂式高空作业平台</a></li>
		<li><a href="#">曲臂式高空作业平台</a></li>
		<li><a href="#">高位取货车</a></li>
		<li><a href="#">工业用梯</a></li>
		</ul>
		<ul class="tab_conbox" id="tab_conbox2">
			<li class="tab_con">
			<img src="assets/6.jpg" />
			<img src="assets/6.jpg" />
			<img src="assets/6.jpg" />
			<img src="assets/6.jpg" />
			</li>
			<li class="tab_con">
			<img src="assets/6.jpg"/>
			</li>
<li class="tab_con">
			<img src="assets/2.jpg"/>
<img src="assets/2.jpg"/>
<img src="assets/2.jpg"/>
			</li>
		</ul>
	</div>
</div>
<div class="footer-nav">
	<div class="about-us">
	<ul>
		<li>关于我们</li>
	</ul>
	<img src="/assets/1.jpg" />
	<div class="span-font">
	<span>
		ROBT在工业设备扩
		展的谈说道路上走出了
		一条技术领先的道路,
		ROBT在工业设备扩
		展的谈说道路上走出
		了一条技术领先的道
	</span>
</div>
</div>
<div class="new-robt">
	<ul>
		<li>新闻中心</li>
	</ul>
	<table class="table">
		<tbody>
			<tr><td>关于某些网站盗用公司图片，资料严正声明.</td></tr>
			<tr><td>热烈庆祝罗倍拓国内销售额翻番</td></tr>
			<tr><td>物料搬运设备市场，ROBT持续稳重求进</td></tr>
		</tbody>
	</table>
</div>
<div class="mulu">
	<ul>
		<li>免费索取工业设备目录</li>
	</ul>
	<img src="/assets/2.jpg" />
</div>
</div>
<div class="footer-list">
	<div class="list-nav">
		<h3>市场策略</h3>
		<ul>
			<li>产品体系</li>
			<li>高端设计</li>
			<li>品牌策略</li>
			<li>直销模式</li>
			<li>品牌优势</li>
			<li>租赁业务</li>
			<li>持续发展</li>
		</ul>
</div>
<div class="list-nav">
		<h3>产品展示</h3>
		<ul>
			<li>产品关键字</li>
			<li>下载专区</li>
			<li>视频展示</li>
			<li>产品目录</li>
		</ul>
</div>
<div class="list-nav">
		<h3>专业知识</h3>
		<ul>
			<li>物料搬运知识</li>
			<li>高空作业平台</li>
			<li>起重吊运知识</li>
			<li>环保节能产品</li>
			<li>工业产品知识</li>
			<li>售后保养知识</li>
		</ul>
</div>
<div class="list-nav">
		<h3>服务中心</h3>
		<ul>
			<li>服务概述</li>
			<li>服务特点</li>
			<li>客户价值</li>
			<li>售后服务</li>
			<li>展厅及OEM基地</li>
			<li>行业应用</li>
		</ul>
</div>
<div class="list-nav">
		<h3>应用案例</h3>
		<ul>
			<li>精选案例</li>
			<li>物流运输</li>
			<li>服务行业</li>
			<li>汽车行业</li>
			<li>食品化工</li>
			<li>加工制造</li>
		</ul>
</div>
</div>
<div class="footer-youshi">
<div class="youshi">
	<img src="/assets/rails.png">
	<div class="footer-font">
		<span>货到付款</span>
		<br />
		<small>先收货再付款，放心购买</small>
	</div>
</div>
<div class="youshi">
	<img src="/assets/rails.png">
	<div class="footer-font">
		<span>50000现货</span>
		<br />
		<small>现货产品4点前下单当天发货</small>
	</div>
</div>
<div class="youshi">
	<img src="/assets/rails.png">
	<div class="footer-font">
		<span>满500免运费</span>
		<br />
		<small>部分区域订单满500免运费</small>
	</div>
</div>
<div class="youshi">
	<img src="/assets/rails.png">
	<div class="footer-font">
		<span>增值税专用发票</span>
		<br />
		<small>可提供增值税专用发票</small>
	</div>
</div>
<div class="youshi">
	<img src="/assets/rails.png">
	<div class="footer-font">
		<span>7天无理由退换货</span>
		<br />
		<small>安心采购，售后无忧</small>
	</div>
</div>
</div>
<div class="nav-footer">
	<ul>
		<li>联系我们 </li>
		<li>产品中心 </li>
		<li>新闻中心  </li>
		<li>销售条款  </li>
		<li>网站地图  </li>
		<li>帮助中心  </li>
	</ul>
</div>
<div class="category-list">
	<span>推荐词条：</span>
	<br />
	<% Category.all.each do |cate|%>
		<span><%= cate.name %> | </span>
		<% cate.tags.each do |tag| %>
			<span><%= tag.name %> |</span>
			<% tag.lists.each do |list| %>
				<span>	<%= list.name %></span>
			<% end %>
		<% end %>
	<% end %>
	<% Category.all.each do |cate|%>
		<span><%= cate.name %> | </span>
		<% cate.tags.each do |tag| %>
			<span><%= tag.name %> |</span>
			<% tag.lists.each do |list| %>
				<span>	<%= list.name %></span>
			<% end %>
		<% end %>
	<% end %>

	</div>
<div class="footer-bottom">
	<span>版权所有：上海罗倍拓工业设备有限公司 高空作业平台 适用于中国客户的内容设计</span><br />
	<span>地址：上海漕河泾开发区松江高科技园区</span><br />
	<span>全国服务热线：4008-8826-918</span><br />
	<span>法律通告,隐私条款 沪ICP备11004282号</span>
</div>



<!--正文-->
<div id="myCarousel" class="carousel slide">
<ol class="carousel-indicators">
	<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	<li data-target="#myCarousel" data-slide-to="1"></li>
	<li data-target="#myCarousel" data-slide-to="2"></li>
</ol>
<!-- Carousel items -->
<div class="carousel-inner">
	<div class="active item"><img src="/assets/1.jpg"></div>
	<div class="item"><img src="/assets/2.jpg"></div>
	<div class="item"><img src="/assets/6.jpg"></div>
</div>
<!-- Carousel nav -->
<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<script>
	$('.carousel').carousel({
		  interval: 5000
		})
</script>
<div class="well">
	<h5 style="text-align: center">关注最多</h2>
</div>
<div class="row-fluid">
	<ul class="thumbnails">
		<% Product.order("liked_count desc").limit(4).each do |product| %>
			<li>
			<div class="thumbnail">
				<%= link_to image_tag(product.photos.first.image_url),product%>
				<h5>	<%= product.title %></h5>
				<small><%= product.number %></small>
				<small><%= product.use %></small>
				<p><%= truncate(product.content, length: 24) %></p>
			</div>
			</li>
		<% end %>
	</ul>
</div>
<div class="well">
	<h5 style="text-align: center">访问最多</h2>
</div>
<%= render partial: 'product_users/visit_list', locals: {products: @products} %>