config/routes.rb
York::Application.routes.draw do
  

  

 	scope '(:locale)' do
		mount RailsAdmin::Engine => '/members', :as => 'rails_admin'
		devise_for :admins
		devise_for :users
		delete 'likes/:resource_name/:resource_id' => "likes#destroy", as: 'like'
		post 'likes/:resource_name/:resource_id' => "likes#create", as: 'like'
		mount Ckeditor::Engine => '/ckeditor'
		resources :abouts
    resources :servers
		resources :topics
		match '/contact' => 'topics#contact'
		resource :cart
		resources :line_items
		resources :products
		resources :product_users
		resources :orders
		resources :customers
		resources :categories
		resources :directories
		match '/tags' => 'categories#tags'
		match 'visit' => 'product_users#visit'
		match '/like' => 'products#like'
		match '/liked' => 'products#liked'
		match '/search' => 'products#search'
		root to: 'home#index'
	end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	attr_accessible :user_id, :directories_attributes, :province_id, :city_id, :district_id, :address
	belongs_to :province
	belongs_to :city
	belongs_to :district
	belongs_to :user
	has_many :directories
	accepts_nested_attributes_for :directories
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_filter :authenticate_user!	
	before_filter :find_user

	def index
	end

	def show
		@customer = @user.customer
	end

	def edit
		@customer = @user.customer
	end

	def new
		@customer = @user.build_customer
		@customer.directories.build
	end

	def create
		@customer = @user.build_customer(params[:customer])
		if @customer.save
			redirect_to @customer
		else
			render 'new'
		end
	end

	def update
		@customer = @user.customer(params[:id])
		if @customer.update_attributes(params[:customer])
			redirect_to @customer
		else
			render 'edit'
		end
	end

	private

	def find_user
		@user = current_user
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
	<% if @customer.errors.any? %>
			<div id="error_explanation">
				<h3><%= t('.have') %>
					<%= @customer.errors.count %>
					<%= t('.number') %>
					<%= t('.error') %>
					<%= t('.prohibited_this_directory_from_being_saved') %></h3>
				<ul>
					<% @customer.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

	<%= f.fields_for :directories do |f| %>
		<%= render partial: "directories/list", locals: {f: f} %>
	<% end %>
	<div class="field field-address">
			<%= f.label :address, "邮寄地址" %>
			<%= collection_select(:customer, :province_id, Province.all, :id, :name) %>
			<%= grouped_collection_select(:customer, :city_id, Province.all, :cities, :id, :id, :name) %>
			<%= grouped_collection_select(:customer, :district_id, City.all, :districts, :id, :id, :name) %>
		</div>
		<div class="field-address">
			<%= f.text_field :address %>
		</div>
	<div class="form-action">
		<%= f.submit "Sbumit", class: "btn btn-success" %>
	</div>
<% end %>
<script type="text/javascript">
	$(document).ready(function(){
		$('#customer_city_id').linkSelect();
		$('#customer_district_id').linkSelect();
	});
	</script>

app/views/customers/edit.html.erb
<%= render 'form' %>

app/views/customers/new.html.erb
<%= render 'form' %>

app/views/customers/show.html.erb
<h3>个人中心信息</h3>
<div class="user-layout">
	<table class="table">
	

			<dt>用户名：<%= @user.name %></dt>
			<dt>邮箱：<%= @user.email %></dt>
			<% if @customer.nil?  %>
				<%= link_to "完善个人信息", new_customer_path(@customer), class: "btn btn-success" %>
			<% else %>
	<tr>
			<td><%= link_to "编辑个人信息", edit_customer_path, class: "btn btn-primary"%></td>
		<tr>
					<% @customer.directories.each do |dir| %>
	<dt>公司：<%= dir.company %></dt>
	<dt>手机：<%= dir.phone %></dt>
	<dt>电话：<%= dir.telphoneumber %></dt>
<% end %>
<dt>地址: 
<%= @customer.province.name %>
<%= @customer.city.name %>
<%= @customer.district.name %>
</dt>
<dt><%= @customer.address %></dt>
</tr>
<% end %>
</table>
</div>