config/routes.rb
York::Application.routes.draw do
  

  

 	scope '(:locale)' do
		mount RailsAdmin::Engine => '/members', :as => 'rails_admin'
		devise_for :admins
		devise_for :users
		delete 'likes/:resource_name/:resource_id' => "likes#destroy", as: 'like'
		post 'likes/:resource_name/:resource_id' => "likes#create", as: 'like'
		mount Ckeditor::Engine => '/ckeditor'
		resources :abouts
    resources :servers
		resources :topics
		match '/contact' => 'topics#contact'
		resource :cart
		resources :line_items
		resources :products
		resources :product_users
		resources :orders
		resources :customers
		resources :categories
		resources :directories
		match '/tags' => 'categories#tags'
		match 'visit' => 'product_users#visit'
		match '/like' => 'products#like'
		match '/liked' => 'products#liked'
		match '/search' => 'products#search'
		root to: 'home#index'
	end

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id             :integer          not null, primary key
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  remember_token :string(255)
#

class Cart < ActiveRecord::Base
  # attr_accessible :title, :bodyhas_many :line_items, dependent: :destroy
	belongs_to :user
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_items
		line_items.sum(:quantity)
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def show
		@cart = find_cart
	end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_list.html.erb
<% if @cart.line_items.empty? %>
	<small style="color: red">还没有添加任何的产品</small>
<% else %>
<table class="table">
		<% @cart.line_items.each do |item| %>
		<tr>
			<td><%= link_to image_tag(item.product.photos.first.image_url), product_path(item.product) %></td>
			<td><%= link_to item.product.title, product_path(item.product) %></td>
			<td><%= item.quantity %></td>
		</tr>
<% end %>
<div class="button-cart index-cart">
	<%= link_to "点击咨询", new_order_path, method: :get, class: "btn btn-primary btn-mini"%>
<%= link_to "empty cart", cart_path(@cart), method: :delete, confirm: "确定删除", class: "btn btn-danger btn-mini" %> 
</div>
</table>
<% end %>

app/views/carts/index.html.erb
<%= render 'list' %>

app/views/carts/show.html.erb
#encoding:utf-8
<div class="button-cart">
<div>Cart</div>
<table class="table">
		<% @cart.line_items.each do |item| %>
		<tr>
			<td><%= item.product.title %></td>
			<td><%= item.quantity %></td>
		</tr>
	<% end %>
	<div class="button-cart">
	<%= link_to "付款", new_order_path, method: :get, class: "btn btn-primary"%>
<%= link_to "empty cart", cart_path(@cart), method: :delete, confirm: "确定删除", class: "btn btn-danger" %> 
</div>
</table>