config/routes.rb
York::Application.routes.draw do
  

  

 	scope '(:locale)' do
		mount RailsAdmin::Engine => '/members', :as => 'rails_admin'
		devise_for :admins
		devise_for :users
		delete 'likes/:resource_name/:resource_id' => "likes#destroy", as: 'like'
		post 'likes/:resource_name/:resource_id' => "likes#create", as: 'like'
		mount Ckeditor::Engine => '/ckeditor'
		resources :abouts
    resources :servers
		resources :topics
		match '/contact' => 'topics#contact'
		resource :cart
		resources :line_items
		resources :products
		resources :product_users
		resources :orders
		resources :customers
		resources :categories
		resources :directories
		match '/tags' => 'categories#tags'
		match 'visit' => 'product_users#visit'
		match '/like' => 'products#like'
		match '/liked' => 'products#liked'
		match '/search' => 'products#search'
		root to: 'home#index'
	end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  number      :string(255)
#  content     :text
#  use         :string(255)
#  load        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  view_count  :integer          default(0)
#  liked_count :integer          default(0)
#  list_id     :integer
#

class Product < ActiveRecord::Base
	include Likeable
  attr_accessible :content, :load, :number, :title, :use, :photos_attributes, :liked_count, :list_id
	validates :title, presence: true, length: { maximum: 50 }
	validates :number, presence: true, uniqueness: true
	validates :content, presence: true
	validates :use, presence: true
	validates :load, presence: true

	has_many :photos
	has_many :line_items
	belongs_to :list
	has_many :product_users
	accepts_nested_attributes_for :photos


	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
	before_filter :authenticate_user!, only: [:like]
	def index
		unless params[:t]
			@products = Product.order("updated_at desc").paginate(page: params[:page], per_page: 4)
		else
			@products = Product.where("list_id = ? ", params[:t]).order("liked_count desc").paginate(page: params[:page], per_page: 4)
		end
			@products.each do |product|
				product.photos.build
			end
	end

	def show
		@product = Product.find(params[:id])
		@product.increment!(:view_count)
	end

	def like
		@user = current_user
		@products = @user.all_liked(Product).order("liked_count desc")
	end
	
	def liked
		@products = Product.order("liked_count desc").paginate(page: params[:page], per_page: 4)
	end	

	def search 
		begin
		@products = Product.where("title like ? or number like ?",
		'%'+params[:q]+'%','%'+params[:q]+'%').order("id desc").paginate(page: params[:page], per_page: 12)

			if @products.empty?
				redirect_to products_path, notice: t("products.no_match_products")
			else
				render 'index'
			end
		end
	end

	def new
		@product = Product.new
		@product.photos.build
	end

	def edit
		@product = Product.find(params[:id])
	end

	def create
		@product = Product.new(params[:product])
		if @product.save
			redirect_to products_path
		else
			render 'new'
		end
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to product_path
		else
			render 'edit'
	end
	end


	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

end

app/helpers/products_helper.rb
module ProductsHelper
	def product?
		@list = List.find_by_id(params[:id])
	end
end

app/views/products/_form.html.erb
<%= form_for(@product, html: {multipart: true}) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= t('.have') %>
				<%= @product.errors.count %>
				<%= t('.number') %>
				<%= t('.error') %>
				<%= t('.prohibited_this_product_from_being_saved') %></h2>
			<ul>
				<% @product.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>
	<span>选择大类:</span> 
	<%= collection_select(:tag, :category_id, Category.all, :id, :name) %><br />
	<span>选择标签:</span>
	<%= grouped_collection_select(:tag, :tag_id, Category.all, :tags, :id, :id, :name) %><br />
	<span>选择分类:</span>
	<%= grouped_collection_select(:product, :list_id, Tag.all, :lists, :id, :id, :name) %><br />
	<div class="field">
		<%= f.label :number %><br />
		<%= f.text_field :number %>
	</div>
	<div class="field">
		<%= f.label :use %><br />
		<%= f.text_field :use %>
	</div>
	<div class="field">
		<%= f.label :load %><br />
		<%= f.text_field :load %>
	</div>
	<div class="field">
		<%= f.fields_for :photos do |photo| %>
			<%= photo.label :image %><br />
			<%= photo.file_field :image %>
		<% end %>
	</div>
	<div class="field">
		<%= f.label :content %><br />
		<%= javascript_include_tag "ckeditor/ckeditor.js" %>
		<%= f.cktext_area("content", width: '100%') %>
	</div>
	<div class="form-action">
		<%= f.submit t('.submit'),class: "btn btn-success" %>  <%= link_to t('.back'), products_path, class: "btn btn-primary" %>
	</div>	
<% end %>

<script type="text/javascript">
	$(document).ready(function(){
		$('#tag_tag_id').linkSelect();
		$('#product_list_id').linkSelect();
	});
</script>

app/views/products/_like_view.html.erb
<li>
<div class="thumbnail">
	<%= link_to image_tag(product.photos.first.image_url),product %>
	<div class="caption">
		<h5><%= product.title %></h5>
		<small><%= product.number %></small>
		<small><%= product.use %></small>
		<p><%= raw truncate(product.content, length: 13) %></p>
	</div>
	<%= button_to t('.cart'), line_items_path(product_id: product), class: "btn" %>

</div>
</li>

app/views/products/_liked_list.html.erb
<%= render partial: 'products/list', locals: {products: @products} %>

app/views/products/_list.html.erb
<div class="row-fluid">
	<ul class="thumbnails">
		<% products.each do |product| %>
			<%= render partial: 'products/like_view', locals: {product: product} %>
			<% end %>
	</ul>
</div>

app/views/products/_nav_list.html.erb
<div class="nav-list nav">
	<h4>产品目录</h4>
	<ul>
		<% Category.all.each do |cate| %>
			<li>	<%= link_to cate.name, category_path(cate.id) %>
					<ul>
				<% cate.tags.each do |tag| %>
					<li>
					<%= link_to tag.name, tags_path(t:tag) %><br />
					<% tag.lists.each do |list| %>
						<%= link_to list.name, products_path(t:list) %>
					<% end %>
		<% end %>
		</li>
	</ul>
	<i class="icon-chevron-right"></i>

	</li>
		<% end %>
	</ul>
</div>

app/views/products/index.html.erb
#encoding:utf-8
<% provide(:title, t('.product')) %>
	<% if product? %>
	<div class="alert alert-error"><strong style="text-align: center">什么也没有</strong></div>
<% else %>
<div id="location">
	<ul class="nav nav-list affix" data-spy="affix", data-offset-top="150">
		<li>产品目录</li>
		<% @products.each do |product| %>
				<li><%= link_to product.list.name, products_path(t:product)%>
			<i class="icon-chevron-right"></i>
			</li>
		<% end %>
	</ul>
</div>
<div class="mylocation">
<%= render partial: 'products/list', locals: {products: @products} %>
<%= will_paginate @products %>
<%= link_to t('.new_product'), new_product_path %>
</div>
<% end %>

app/views/products/like.html.erb
<% if @user.all_liked(Product).nil? %>
	<p>ds</p>
<% else %>
	<%= render partial: "products/list", locals: {products: @products } %>
<% end %>

app/views/products/liked.html.erb
<%= render partial: 'products/liked_list', loclas: {products: @products} %>

app/views/products/new.html.erb
<%= render 'form' %>
<%= link_to t('.back'), :back,class: "btn btn-primary" %> 

app/views/products/show.html.erb
#encoding:utf-8
<div class="span12">
	<%= @product.title %><br />
	<% @product.photos.each do |photo| %>
		<%= image_tag(photo.image_url) %>
	<% end %> <br />
	<%= @product.number %><br />
	<%= @product.use %>
	<%= @product.load %><br />
	<%= @product.view_count %><br />
	<%= raw @product.content %><br />
	<%= link_to t('.back'), products_path, class: "btn btn-primary" %> 
	<%= link_to t('.edit'), edit_product_path(@product),class: "btn btn-info" %>
</div>